const BALL_PLAYBACK_RATE = 0.9;
const BALL_FRAME_INTERVAL_MS = 60 / BALL_PLAYBACK_RATE;
const BALL_POST_CLEAR_DELAY_MS = 120 / BALL_PLAYBACK_RATE;
const BALL_PRE_CLEAR_DELAY_MS = 180;
const BALL_HOP_FRAME_INTERVAL_MS = 50 / BALL_PLAYBACK_RATE;
const BALL_HOP_CONTACT_FRAME = 1;
const BALL_SPAWN_FRAMES = Object.freeze([6, 7]);
const BALL_REMOVAL_FRAMES = Object.freeze([8, 9]);
const GAME_OVER_REMOVAL_FRAME_MS = 90;
const GAME_OVER_REMOVAL_HOLD_MS = 60;
const PILLAR_RISE_INTERVAL_MS = 15;
const OPPONENT_DEFEAT_INTERVAL_MS = 110;
const OPPONENT_RETIRE_INTERVAL_MS = 20;
const OPPONENT_ENTRANCE_DELAY_MS = 120;
const OPPONENT_ENTRANCE_INTERVAL_MS = 35;
const CORONATION_FRAME_INTERVAL_MS = 120;
const VICTORY_SWING_INTERVAL_MS = 600;
const VICTORY_SWING_COUNT = 3;

export {
  BALL_FRAME_INTERVAL_MS,
  BALL_POST_CLEAR_DELAY_MS,
  BALL_PRE_CLEAR_DELAY_MS,
  BALL_HOP_FRAME_INTERVAL_MS,
  BALL_HOP_CONTACT_FRAME,
  BALL_SPAWN_FRAMES,
  BALL_REMOVAL_FRAMES,
  GAME_OVER_REMOVAL_FRAME_MS,
  GAME_OVER_REMOVAL_HOLD_MS,
  PILLAR_RISE_INTERVAL_MS,
  OPPONENT_DEFEAT_INTERVAL_MS,
  OPPONENT_RETIRE_INTERVAL_MS,
  OPPONENT_ENTRANCE_DELAY_MS,
  OPPONENT_ENTRANCE_INTERVAL_MS,
  CORONATION_FRAME_INTERVAL_MS,
  VICTORY_SWING_INTERVAL_MS,
  VICTORY_SWING_COUNT,
};
