const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
const { generateFonts } = require('./generate-fonts.cjs');
const { pathToFileURL } = require('node:url');
const { loadAndValidateLocales } = require('./validate-locales.cjs');
const root = path.join(__dirname, '..');

async function build() {
  const { locales, document } = loadAndValidateLocales();
  const { WEB_RELEASE } = await import(pathToFileURL(path.join(root, 'src/core/release.js')));
  const font = generateFonts();
  const bundle = await esbuild.build({
    absWorkingDir: root,
    entryPoints: ['src/start.js'],
    bundle: true,
    format: 'iife',
    target: 'es2022',
    charset: 'utf8',
    write: false,
    loader: { '.png': 'dataurl' },
    legalComments: 'inline',
  });
  const slots = {
    INLINE_ABOUT_LOGO: `<img class="about-logo" width="67" height="50" alt="GAMOS" src="data:image/png;base64,${fs.readFileSync(path.join(root, 'src/assets/gamos-logo.png')).toString('base64')}" />`,
    INLINE_STYLES: `<style>\n${font.css}\n${fs.readFileSync(path.join(root, 'src/styles.css'), 'utf8')}\n</style>`,
    INLINE_LICENSES: `<!--\n${font.licenses}\n-->`,
    INLINE_SCRIPT: `<script>\n${bundle.outputFiles[0].text.replace(/<\/script/gi, '<\\/script')}\n</script>`,
  };
  for (const element of document.querySelectorAll('[data-i18n]'))
    element.textContent = locales.en[element.getAttribute('data-i18n')].replaceAll(
      '{webRelease}',
      WEB_RELEASE,
    );
  for (const [attribute, target] of [
    ['data-i18n-title', 'title'],
    ['data-i18n-aria-label', 'aria-label'],
  ])
    for (const element of document.querySelectorAll(`[${attribute}]`))
      element.setAttribute(
        target,
        locales.en[element.getAttribute(attribute)].replaceAll('{webRelease}', WEB_RELEASE),
      );
  let html = document.toString();
  for (const [name, content] of Object.entries(slots)) {
    const marker = `<!-- ${name} -->`;
    if (html.split(marker).length !== 2) throw Error(`Expected one ${name} slot in src/index.html`);
    html = html.replace(marker, () => content);
  }
  html = html.replace(
    /<!doctype html>/i,
    '<!doctype html>\n<!-- Generated by npm run build in h5/. Edit h5/src/, not this file. -->',
  );
  fs.writeFileSync(path.join(root, '../index.html'), html);
  console.log('Built index.html: offline styles, sprites, fonts and JavaScript.');
}

if (require.main === module)
  build().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
module.exports = { build };
