// Generate one font data module and its offline CSS/license payload for the build.
const fs = require('node:fs');
const path = require('node:path');
const { glyphs, css } = require('./build-pixel-font.cjs');
const locales = require('./locales.json');
const font = require('./fusion-pixel-glyphs.json');
const { packPixelGlyphs, splitSharedGlyphs } = require('./pack-pixel-glyphs.cjs');

function generateFonts() {
  const required = new Set(
    [...(JSON.stringify(locales) + '简体中文繁體中文')].filter(
      (character) => character.codePointAt(0) > 127 && !glyphs[character],
    ),
  );
  for (const locale of ['zh-Hans', 'zh-Hant']) {
    for (const character of required) {
      const rows = font.glyphs[locale][character];
      if (
        !rows ||
        rows.length !== font.pixelSize ||
        rows.some((row) => !/^[01]+$/.test(row) || row.length !== rows[0].length)
      ) {
        throw Error(
          `Missing or invalid ${locale} glyph: ${character}. Run tools/import-fusion-font.cjs.`,
        );
      }
    }
  }
  const generated = path.join(__dirname, '../src/generated');
  fs.mkdirSync(generated, { recursive: true });
  const values = {
    PIXEL_GLYPHS: glyphs,
    LOCALES: locales,
  };
  const { shared, simplifiedOnly, traditionalOnly } = splitSharedGlyphs(
    font.glyphs['zh-Hans'],
    font.glyphs['zh-Hant'],
  );
  fs.writeFileSync(
    path.join(generated, 'fonts.js'),
    '// Generated by tools/generate-fonts.cjs. Do not edit.\n' +
      "import { unpackPixelGlyphs } from '../core/pixel-glyph-codec.js';\n" +
      Object.entries(values)
        .map(([name, value]) => `export const ${name} = ${JSON.stringify(value)};`)
        .join('\n') +
      '\n' +
      `const shared = unpackPixelGlyphs(${JSON.stringify(packPixelGlyphs(shared))});\n` +
      `export const CJK_GLYPHS = { ...shared, ...unpackPixelGlyphs(${JSON.stringify(packPixelGlyphs(simplifiedOnly))}) };\n` +
      `export const CJK_TRADITIONAL_GLYPHS = { ...shared, ...unpackPixelGlyphs(${JSON.stringify(packPixelGlyphs(traditionalOnly))}) };\n`,
  );
  const licenseRoot = path.join(__dirname, '../licenses/fusion-pixel');
  const licenses = fs
    .readdirSync(licenseRoot, { recursive: true })
    .sort()
    .filter((name) => fs.statSync(path.join(licenseRoot, name)).isFile())
    .map(
      (name) =>
        `${name.replaceAll('\\', '/')}\n${fs.readFileSync(path.join(licenseRoot, name), 'utf8')}`,
    )
    .join('\n\n');
  return { css, licenses: `Fusion Pixel ${font.version}\n${font.source}\n${licenses}` };
}

module.exports = { generateFonts };
